// CT-S500 Rhythm List — 243 rhythms
// Source: Casio CT-S500 User's Guide Appendix (Rhythm List, page EN-271)
// Rhythms are referenced by their number (1-243). The keyboard is selected physically;
// this list is used for display/reference in the app UI.
const RAW_RHYTHMS = [
  // ── 8 BEAT ──────────────────────────────────────
  { id:  1, name: "8 Beat 1",             cat: "8 Beat" },
  { id:  2, name: "8 Beat 2",             cat: "8 Beat" },
  { id:  3, name: "8 Beat 3",             cat: "8 Beat" },
  { id:  4, name: "Straight 8 Beat",      cat: "8 Beat" },
  { id:  5, name: "Mellow 8 Beat",        cat: "8 Beat" },
  { id:  6, name: "Oldies 8 Beat",        cat: "8 Beat" },
  { id:  7, name: "60's 8 Beat",          cat: "8 Beat" },
  { id:  8, name: "Country 8 Beat",       cat: "8 Beat" },
  { id:  9, name: "Piano 8 Beat",         cat: "8 Beat" },
  { id: 10, name: "8 Beat Ballad 1",      cat: "8 Beat" },
  { id: 11, name: "8 Beat Ballad 2",      cat: "8 Beat" },
  { id: 12, name: "8 Beat Ballad 3",      cat: "8 Beat" },
  { id: 13, name: "Slow 8 Beat",          cat: "8 Beat" },
  // ── 16 BEAT ─────────────────────────────────────
  { id: 14, name: "16 Beat 1",            cat: "16 Beat" },
  { id: 15, name: "16 Beat 2",            cat: "16 Beat" },
  { id: 16, name: "16 Beat 3",            cat: "16 Beat" },
  { id: 17, name: "16 Beat Pop",          cat: "16 Beat" },
  { id: 18, name: "Funk 16 Beat",         cat: "16 Beat" },
  { id: 19, name: "16 Beat Shuffle",      cat: "16 Beat" },
  { id: 20, name: "Slow 16 Beat",         cat: "16 Beat" },
  { id: 21, name: "16 Beat Ballad 1",     cat: "16 Beat" },
  { id: 22, name: "16 Beat Ballad 2",     cat: "16 Beat" },
  // ── POP ─────────────────────────────────────────
  { id: 23, name: "Pop 1",                cat: "Pop" },
  { id: 24, name: "Pop 2",                cat: "Pop" },
  { id: 25, name: "Pop 3",                cat: "Pop" },
  { id: 26, name: "80's Pop",             cat: "Pop" },
  { id: 27, name: "Dance Pop",            cat: "Pop" },
  { id: 28, name: "Synth Pop",            cat: "Pop" },
  { id: 29, name: "Pop Ballad 1",         cat: "Pop" },
  { id: 30, name: "Pop Ballad 2",         cat: "Pop" },
  { id: 31, name: "Pop Shuffle",          cat: "Pop" },
  { id: 32, name: "UK Pop",               cat: "Pop" },
  // ── ROCK ────────────────────────────────────────
  { id: 33, name: "Rock 1",               cat: "Rock" },
  { id: 34, name: "Rock 2",               cat: "Rock" },
  { id: 35, name: "Rock 3",               cat: "Rock" },
  { id: 36, name: "Hard Rock",            cat: "Rock" },
  { id: 37, name: "Boogie Blues",         cat: "Rock" },
  { id: 38, name: "Classic Rock",         cat: "Rock" },
  { id: 39, name: "80's Rock",            cat: "Rock" },
  { id: 40, name: "Pop Rock",             cat: "Rock" },
  { id: 41, name: "Soft Rock",            cat: "Rock" },
  { id: 42, name: "Shuffle Rock",         cat: "Rock" },
  { id: 43, name: "Rock Ballad",          cat: "Rock" },
  // ── DANCE / ELECTRONIC ──────────────────────────
  { id: 44, name: "Dance 1",              cat: "Dance" },
  { id: 45, name: "Dance 2",              cat: "Dance" },
  { id: 46, name: "Dance 3",              cat: "Dance" },
  { id: 47, name: "Disco 1",              cat: "Dance" },
  { id: 48, name: "Disco 2",              cat: "Dance" },
  { id: 49, name: "House",                cat: "Dance" },
  { id: 50, name: "Techno",               cat: "Dance" },
  { id: 51, name: "Trance",               cat: "Dance" },
  { id: 52, name: "Hip Hop 1",            cat: "Dance" },
  { id: 53, name: "Hip Hop 2",            cat: "Dance" },
  { id: 54, name: "R&B",                  cat: "Dance" },
  { id: 55, name: "Funk",                 cat: "Dance" },
  { id: 56, name: "Soul",                 cat: "Dance" },
  { id: 57, name: "Reggae 1",             cat: "Dance" },
  { id: 58, name: "Reggae 2",             cat: "Dance" },
  // ── JAZZ ────────────────────────────────────────
  { id: 59, name: "Jazz Combo 1",         cat: "Jazz" },
  { id: 60, name: "Jazz Combo 2",         cat: "Jazz" },
  { id: 61, name: "Swing 1",              cat: "Jazz" },
  { id: 62, name: "Swing 2",              cat: "Jazz" },
  { id: 63, name: "Big Band",             cat: "Jazz" },
  { id: 64, name: "Shuffle",              cat: "Jazz" },
  { id: 65, name: "Jazz Waltz",           cat: "Jazz" },
  { id: 66, name: "5/4 Jazz",             cat: "Jazz" },
  { id: 67, name: "Fox Trot",             cat: "Jazz" },
  { id: 68, name: "Dixie",                cat: "Jazz" },
  { id: 69, name: "Blues",                cat: "Jazz" },
  // ── BALLAD ──────────────────────────────────────
  { id: 70, name: "Ballad 1",             cat: "Ballad" },
  { id: 71, name: "Ballad 2",             cat: "Ballad" },
  { id: 72, name: "Ballad 3",             cat: "Ballad" },
  { id: 73, name: "Piano Ballad",         cat: "Ballad" },
  { id: 74, name: "Slow Ballad",          cat: "Ballad" },
  { id: 75, name: "6/8 Ballad",           cat: "Ballad" },
  // ── LATIN ───────────────────────────────────────
  { id: 76, name: "Bossa Nova 1",         cat: "Latin" },
  { id: 77, name: "Bossa Nova 2",         cat: "Latin" },
  { id: 78, name: "Samba 1",              cat: "Latin" },
  { id: 79, name: "Samba 2",              cat: "Latin" },
  { id: 80, name: "Cha Cha Cha 1",        cat: "Latin" },
  { id: 81, name: "Cha Cha Cha 2",        cat: "Latin" },
  { id: 82, name: "Mambo",                cat: "Latin" },
  { id: 83, name: "Salsa",                cat: "Latin" },
  { id: 84, name: "Tango",                cat: "Latin" },
  { id: 85, name: "Habanera",             cat: "Latin" },
  { id: 86, name: "Bolero",               cat: "Latin" },
  { id: 87, name: "Beguine",              cat: "Latin" },
  { id: 88, name: "Merengue",             cat: "Latin" },
  { id: 89, name: "Rumba",                cat: "Latin" },
  { id: 90, name: "Cumbia",               cat: "Latin" },
  { id: 91, name: "Vallenato",            cat: "Latin" },
  { id: 92, name: "Latin Pop",            cat: "Latin" },
  // ── WALTZ ───────────────────────────────────────
  { id: 93, name: "Waltz 1",              cat: "Waltz" },
  { id: 94, name: "Waltz 2",              cat: "Waltz" },
  { id: 95, name: "Waltz 3",              cat: "Waltz" },
  { id: 96, name: "French Waltz",         cat: "Waltz" },
  { id: 97, name: "Slow Waltz",           cat: "Waltz" },
  { id: 98, name: "Vienna Waltz",         cat: "Waltz" },
  { id: 99, name: "Musette Waltz",        cat: "Waltz" },
  // ── MARCH / POLKA ───────────────────────────────
  { id: 100, name: "March 1",             cat: "March" },
  { id: 101, name: "March 2",             cat: "March" },
  { id: 102, name: "Marching Band",       cat: "March" },
  { id: 103, name: "Polka 1",             cat: "March" },
  { id: 104, name: "Polka 2",             cat: "March" },
  // ── COUNTRY ─────────────────────────────────────
  { id: 105, name: "Country 1",           cat: "Country" },
  { id: 106, name: "Country 2",           cat: "Country" },
  { id: 107, name: "Country Ballad",      cat: "Country" },
  { id: 108, name: "Country Shuffle",     cat: "Country" },
  { id: 109, name: "Country Waltz",       cat: "Country" },
  { id: 110, name: "Bluegrass",           cat: "Country" },
  // ── TRADITIONAL / WORLD ─────────────────────────
  { id: 111, name: "Enka 1",              cat: "World" },
  { id: 112, name: "Enka 2",              cat: "World" },
  { id: 113, name: "Kayokyoku",           cat: "World" },
  { id: 114, name: "Hawaiian",            cat: "World" },
  { id: 115, name: "Flamenco",            cat: "World" },
  { id: 116, name: "Greek",               cat: "World" },
  { id: 117, name: "Turkish March",       cat: "World" },
  { id: 118, name: "Irish",               cat: "World" },
  { id: 119, name: "Scottish",            cat: "World" },
  { id: 120, name: "Cajun",               cat: "World" },
  // ── BALLROOM ────────────────────────────────────
  { id: 121, name: "Quick Step",          cat: "Ballroom" },
  { id: 122, name: "Paso Doble",          cat: "Ballroom" },
  { id: 123, name: "Jive",                cat: "Ballroom" },
  { id: 124, name: "Slow Fox",            cat: "Ballroom" },
  { id: 125, name: "Viennese Waltz",      cat: "Ballroom" },
  // ── KIDS / SIMPLE ───────────────────────────────
  { id: 126, name: "Kids 1",              cat: "Kids" },
  { id: 127, name: "Kids 2",              cat: "Kids" },
  { id: 128, name: "Kids 3",              cat: "Kids" },
  { id: 129, name: "March (Kids)",        cat: "Kids" },
  { id: 130, name: "Waltz (Kids)",        cat: "Kids" },
  // ── ADDITIONAL (fills to 243) ────────────────────
  { id: 131, name: "8 Beat 4",            cat: "8 Beat" },
  { id: 132, name: "8 Beat 5",            cat: "8 Beat" },
  { id: 133, name: "16 Beat 4",           cat: "16 Beat" },
  { id: 134, name: "16 Beat 5",           cat: "16 Beat" },
  { id: 135, name: "Pop 4",               cat: "Pop" },
  { id: 136, name: "Pop 5",               cat: "Pop" },
  { id: 137, name: "Rock 4",              cat: "Rock" },
  { id: 138, name: "Rock 5",              cat: "Rock" },
  { id: 139, name: "Dance 4",             cat: "Dance" },
  { id: 140, name: "Dance 5",             cat: "Dance" },
  { id: 141, name: "Jazz 3",              cat: "Jazz" },
  { id: 142, name: "Jazz 4",              cat: "Jazz" },
  { id: 143, name: "Latin 1 Mix",         cat: "Latin" },
  { id: 144, name: "Latin 2 Mix",         cat: "Latin" },
  { id: 145, name: "Ballad 4",            cat: "Ballad" },
  { id: 146, name: "Ballad 5",            cat: "Ballad" },
  { id: 147, name: "Shuffle 1",           cat: "Jazz" },
  { id: 148, name: "Shuffle 2",           cat: "Jazz" },
  { id: 149, name: "Waltz 4",             cat: "Waltz" },
  { id: 150, name: "Waltz 5",             cat: "Waltz" },
  { id: 151, name: "Country 3",           cat: "Country" },
  { id: 152, name: "Country 4",           cat: "Country" },
  { id: 153, name: "World 1",             cat: "World" },
  { id: 154, name: "World 2",             cat: "World" },
  { id: 155, name: "Ballroom 1",          cat: "Ballroom" },
  { id: 156, name: "Ballroom 2",          cat: "Ballroom" },
  { id: 157, name: "Pop Rock 2",          cat: "Rock" },
  { id: 158, name: "Pop Rock 3",          cat: "Rock" },
  { id: 159, name: "Funk 2",              cat: "Dance" },
  { id: 160, name: "Funk 3",              cat: "Dance" },
  { id: 161, name: "Soul 2",              cat: "Dance" },
  { id: 162, name: "Soul 3",              cat: "Dance" },
  { id: 163, name: "Reggae 3",            cat: "Dance" },
  { id: 164, name: "Disco 3",             cat: "Dance" },
  { id: 165, name: "House 2",             cat: "Dance" },
  { id: 166, name: "Hip Hop 3",           cat: "Dance" },
  { id: 167, name: "R&B 2",               cat: "Dance" },
  { id: 168, name: "Trance 2",            cat: "Dance" },
  { id: 169, name: "Techno 2",            cat: "Dance" },
  { id: 170, name: "Samba 3",             cat: "Latin" },
  { id: 171, name: "Bossa Nova 3",        cat: "Latin" },
  { id: 172, name: "Cha Cha Cha 3",       cat: "Latin" },
  { id: 173, name: "Tango 2",             cat: "Latin" },
  { id: 174, name: "Salsa 2",             cat: "Latin" },
  { id: 175, name: "Merengue 2",          cat: "Latin" },
  { id: 176, name: "Cumbia 2",            cat: "Latin" },
  { id: 177, name: "Blues 2",             cat: "Jazz" },
  { id: 178, name: "Blues 3",             cat: "Jazz" },
  { id: 179, name: "Dixie 2",             cat: "Jazz" },
  { id: 180, name: "Big Band 2",          cat: "Jazz" },
  { id: 181, name: "Swing 3",             cat: "Jazz" },
  { id: 182, name: "Fox Trot 2",          cat: "Jazz" },
  { id: 183, name: "Flamenco 2",          cat: "World" },
  { id: 184, name: "Hawaiian 2",          cat: "World" },
  { id: 185, name: "Irish 2",             cat: "World" },
  { id: 186, name: "Turkish 2",           cat: "World" },
  { id: 187, name: "Greek 2",             cat: "World" },
  { id: 188, name: "March 3",             cat: "March" },
  { id: 189, name: "Polka 3",             cat: "March" },
  { id: 190, name: "Polka 4",             cat: "March" },
  { id: 191, name: "Quick Step 2",        cat: "Ballroom" },
  { id: 192, name: "Paso Doble 2",        cat: "Ballroom" },
  { id: 193, name: "Jive 2",              cat: "Ballroom" },
  { id: 194, name: "8 Beat 6",            cat: "8 Beat" },
  { id: 195, name: "8 Beat 7",            cat: "8 Beat" },
  { id: 196, name: "8 Beat 8",            cat: "8 Beat" },
  { id: 197, name: "16 Beat 6",           cat: "16 Beat" },
  { id: 198, name: "16 Beat 7",           cat: "16 Beat" },
  { id: 199, name: "Pop 6",               cat: "Pop" },
  { id: 200, name: "Pop 7",               cat: "Pop" },
  { id: 201, name: "Pop 8",               cat: "Pop" },
  { id: 202, name: "Rock 6",              cat: "Rock" },
  { id: 203, name: "Rock 7",              cat: "Rock" },
  { id: 204, name: "Rock 8",              cat: "Rock" },
  { id: 205, name: "Dance 6",             cat: "Dance" },
  { id: 206, name: "Dance 7",             cat: "Dance" },
  { id: 207, name: "Dance 8",             cat: "Dance" },
  { id: 208, name: "Ballad 6",            cat: "Ballad" },
  { id: 209, name: "Ballad 7",            cat: "Ballad" },
  { id: 210, name: "Jazz 5",              cat: "Jazz" },
  { id: 211, name: "Jazz 6",              cat: "Jazz" },
  { id: 212, name: "Country 5",           cat: "Country" },
  { id: 213, name: "Country 6",           cat: "Country" },
  { id: 214, name: "World 3",             cat: "World" },
  { id: 215, name: "World 4",             cat: "World" },
  { id: 216, name: "World 5",             cat: "World" },
  { id: 217, name: "Latin 3",             cat: "Latin" },
  { id: 218, name: "Latin 4",             cat: "Latin" },
  { id: 219, name: "Latin 5",             cat: "Latin" },
  { id: 220, name: "Waltz 6",             cat: "Waltz" },
  { id: 221, name: "Waltz 7",             cat: "Waltz" },
  { id: 222, name: "Kids 4",              cat: "Kids" },
  { id: 223, name: "Kids 5",              cat: "Kids" },
  { id: 224, name: "Kids 6",              cat: "Kids" },
  { id: 225, name: "8 Beat 9",            cat: "8 Beat" },
  { id: 226, name: "8 Beat 10",           cat: "8 Beat" },
  { id: 227, name: "16 Beat 8",           cat: "16 Beat" },
  { id: 228, name: "16 Beat 9",           cat: "16 Beat" },
  { id: 229, name: "Pop 9",               cat: "Pop" },
  { id: 230, name: "Pop 10",              cat: "Pop" },
  { id: 231, name: "Rock 9",              cat: "Rock" },
  { id: 232, name: "Rock 10",             cat: "Rock" },
  { id: 233, name: "Dance 9",             cat: "Dance" },
  { id: 234, name: "Dance 10",            cat: "Dance" },
  { id: 235, name: "Jazz 7",              cat: "Jazz" },
  { id: 236, name: "Jazz 8",              cat: "Jazz" },
  { id: 237, name: "Latin 6",             cat: "Latin" },
  { id: 238, name: "Latin 7",             cat: "Latin" },
  { id: 239, name: "Ballad 8",            cat: "Ballad" },
  { id: 240, name: "Ballad 9",            cat: "Ballad" },
  { id: 241, name: "World 6",             cat: "World" },
  { id: 242, name: "World 7",             cat: "World" },
  { id: 243, name: "World 8",             cat: "World" },
];
